name: 'Build LaTex Document with TinyTeX'
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: TinyTeX cache
        with:
          path: |
            $HOME/.TinyTeX
            $HOME/bin
          key: ${{ runner.os }}-TinyTeX-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-TinyTeX-
      - uses: r-lib/actions/setup-tinytex@v2
        env:
          # install minimal version
          TINYTEX_INSTALLER: TinyTeX
      - run: tlmgr --version
      - name: Install LaTeX packages for MaTeX
        run: |
          tlmgr install latex standalone lm svn-prov
          tlmgr list --only-installed
      - name: Test compile
        run: pdflatex simple.tex
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: simple
          path: simple.pdf
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3